version: "3"
services:
  postgres:
    image: "postgres:latest"
    container_name: "${CONTAINER_NAME}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - "${PORT}:${PORT}"
    command: -p "${PORT}"
volumes:
  postgres_data:

networks:
  default:
    name: ${NETWORK_NAME}